import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Footer from '../components/Footer'
import Hiring from '../components/home/hiring'
import Navbar from '../components/Navbar'
import { SITE_TITLE } from '../lib/constants'
import styles from '../styles/Home.module.css'
import {
  faCloud,
  faLanguage,
  faMobile,
  faBitcoinSign,
  faCertificate,
  faMapMarkedAlt,
  faEnvelope,
  faPhone,
} from '@fortawesome/free-solid-svg-icons'

import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { useState } from 'react'
import { submitContactForm } from './api/api-helper'

const Contact: NextPage = () => {
  const [name, setName] = useState<string>('')
  const [email, setEmail] = useState<string>('')
  const [notes, setNotes] = useState<string>('')
  const [message, setMessage] = useState<string>()
  const resetForm = () => {
    setName('')
    setNotes('')
    setEmail('')
  }
  const onSubmit = (name: string, email: string, message: string) => {
    setMessage('processing...')

    const contactInput = {
      name,
      email,
      notes,
      website: 'andmap.co',
    }

    submitContactForm(contactInput)
      .then((result) => {
        resetForm()
        setMessage('Thanks, we will contact you soon.')
      })
      .catch((error) => setMessage(error.message))
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>{SITE_TITLE}</title>

        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Navbar />

      <main className={styles.main}>
        <div className='grid grid-cols-1 gap-4 lg:grid-cols-2'>
          <div className='p-16'>
            <h2 className='text-[40px] text-bold pb-10'>Contact</h2>

            <p>
              We appreciated your time and we offer a free quote for your
              project. We can have an office meeting if you are local to talk
              about your requirements.
              {/* With a comprehensive suite of Web,
              Mobile, IoT, and general software services, Andmap has the
  expertise your project requires. */}
            </p>
            <div className='bg-veryLightBlue p-2 mt-4 relative '>
              <div className='text-blue text-[20px] mb-2'>ANDMAP, LLC.</div>
              <div>
                <FontAwesomeIcon
                  icon={faPhone}
                  className='text-blue'
                  style={{ fontSize: 14 }}
                />{' '}
                call: (949) 329-2220
              </div>
              <div>
                <FontAwesomeIcon
                  icon={faEnvelope}
                  className='text-blue'
                  style={{ fontSize: 14 }}
                />{' '}
                email: info@andmap.co
              </div>
            </div>
          </div>

          <div className='p-16'>
            <h2 className='text-[30px] text-bold pb-2'>
              Let us hear from you directly!
            </h2>

            <div className='w-[35px] h-[2px] bg-blue mb-8' />
            <p>
              We always want to hear from you! Let us know how we can best help
              you and we will do our very best.
            </p>
            <div className='p-4'>
              <form
                onSubmit={(e) => {
                  e.preventDefault()
                  if (!name || !email || !notes) {
                    setMessage('Please fill in all fields')
                    return
                  }
                  onSubmit(name, email, notes)
                }}
              >
                <div className=' m-2 w-auto'>
                  <input
                    className='w-full border-gray-300'
                    type='text'
                    name='name'
                    placeholder='Name'
                    onChange={(e) => setName(e.target.value)}
                    value={name}
                  />
                </div>
                <div className='m-2'>
                  <input
                    type='email'
                    name='email'
                    className='w-full border-gray-300'
                    placeholder='Email'
                    onChange={(e) => setEmail(e.target.value)}
                    value={email}
                  />
                </div>
                <div className=' m-2'>
                  <textarea
                    name='notes'
                    className='w-full border-gray-300'
                    rows={3}
                    placeholder='Message'
                    onChange={(e) => setNotes(e.target.value)}
                    value={notes}
                  ></textarea>
                </div>
                <div className='flex space-x-2 justify-center'>
                  <button
                    type='submit'
                    className='uppercase inline-block px-6 py-2.5 bg-blue text-white  text-xs leading-tight  hover:bg-blue-700 hover:shadow-lg active:bg-blue-800 active:shadow-lg transition duration-150 ease-in-out'
                  >
                    Send Message
                  </button>
                  <div className='mt-1'>{message}</div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </main>

      <Footer />
    </div>
  )
}

export default Contact
