import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Footer from '../components/Footer'
import Hiring from '../components/home/hiring'
import Navbar from '../components/Navbar'
import { CLIENTS_LOGOS, SITE_TITLE } from '../lib/constants'
import styles from '../styles/Home.module.css'
import {
  faFilePdf,
  faSignature,
  faMobile,
  faHistory,
  faCertificate,
  faMapMarkedAlt,
  faEnvelope,
  faDraftingCompass,
  faFile,
} from '@fortawesome/free-solid-svg-icons'
import Link from 'next/link'

import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { useState } from 'react'
import { submitContactForm } from './api/api-helper'
import Carousel from '../components/common/Carousel'
import OptusDownload from '../components/home/optus-download'
import BannerDownload from '../components/home/banner-download'

const PdfOcr: NextPage = () => {
  const [name, setName] = useState<string>('')
  const [email, setEmail] = useState<string>('')
  const [notes, setNotes] = useState<string>('')
  const [message, setMessage] = useState<string>()
  const resetForm = () => {
    setName('')
    setNotes('')
    setEmail('')
  }
  const onSubmit = (name: string, email: string, message: string) => {
    setMessage('processing...')

    const contactInput = {
      name,
      email,
      notes,
      website: 'andmap.co',
    }

    submitContactForm(contactInput)
      .then((result) => {
        resetForm()
        setMessage('Thanks, we will contact you soon.')
      })
      .catch((error) => setMessage(error.message))
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>{SITE_TITLE}</title>

        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Navbar />

      <main className={styles.main}>
        <div className='grid grid-cols-1 gap-4 lg:grid-cols-2'>
          <div className='p-16'>
            <h2 className='text-[30px] text-bold pb-2'>AMD V2.0</h2>
            <p className='text-[14px] mb-8 text-blue'>
              Andmap MORTGAGE DOCUMENTS app
            </p>
            <p className='text-gray-400'>
              Organizations dealing with mortgages and loans come across
              numerous paper documents like loan applications, forms, legal
              letters, etc. every day which need to be processed and managed
              accurately and on time. A little error during the process can
              cause a significant loss to the company. The main disadvantage
              with manual processing is the long processing time. Moreover, the
              rate of accuracy cannot be guaranteed.{' '}
              <span className='text-blue'>Andmap AMD V2.0</span> is using{' '}
              <span className='text-bold text-black'>OCR</span> technology, scan
              folders or individual file, find missing titles, missing
              signatures, date field or any data based on customized configs.
            </p>
          </div>

          <div className='p-16 '>
            <div className='w-full relative h-96'>
              <Image
                src={'/assets/amd-1.jpeg'}
                alt='PDF OCR for mortgage company'
                layout='fill'
                objectFit='contain'
              />
            </div>
          </div>
        </div>

        <h2 className='text-[30px] text-bold pb-2 uppercase mt-16'>FEATURES</h2>
        <div className='w-[35px] h-[2px] bg-blue ' />
        <div className='grid grid-cols-1 gap-4 lg:grid-cols-4 p-16'>
          <div className='text-center p-4 relative'>
            <span className='inner-block w-20 h-20 rounded-full border-2 border-blue bg-blue inline-flex justify-center items-center mb-4'>
              <FontAwesomeIcon
                icon={faDraftingCompass}
                className='text-white'
                style={{ fontSize: 36 }}
              />{' '}
            </span>
            <h3 className='h5 text-gray-400 uppercase mb-3'>CUSTOMIZED</h3>
            <p className='mb-0'>Multiple configure files</p>
          </div>

          <div className='text-center p-4 relative border-l border-verylightgray'>
            <span className='inner-block w-20 h-20 rounded-full border-2 border-blue bg-blue inline-flex justify-center items-center mb-4'>
              <FontAwesomeIcon
                icon={faSignature}
                className='text-white'
                style={{ fontSize: 36 }}
              />{' '}
            </span>
            <h3 className='h5 text-gray-400 uppercase mb-3'>
              SIGNATURE & DATE
            </h3>
            <p className='mb-0'>
              Extract Signature & Date for custom search phrases
            </p>
          </div>
          <div className='text-center p-4 relative border-l border-bray'>
            <span className='inner-block w-20 h-20 rounded-full border-2 border-blue bg-blue inline-flex justify-center items-center mb-4'>
              <FontAwesomeIcon
                icon={faHistory}
                className='text-white'
                style={{ fontSize: 36 }}
              />{' '}
            </span>
            <h3 className='h5 text-gray-400 uppercase mb-3'>HISTORY</h3>
            <p className='mb-0'>
              Review documents history, compare the date of each version of same
              document
            </p>
          </div>
          <div className='text-center p-4 relative border-l border-bray'>
            <span className='inner-block w-20 h-20 rounded-full border-2 border-blue bg-blue inline-flex justify-center items-center mb-4'>
              <FontAwesomeIcon
                icon={faFilePdf}
                className='text-white'
                style={{ fontSize: 36 }}
              />{' '}
            </span>
            <h3 className='h5 text-gray-400 uppercase mb-3'>
              CREATE FINAL PDF
            </h3>
            <p className='mb-0'>
              Ordering documents, TURN on / off pages, generate Final PDF
            </p>
          </div>
        </div>
        <div className='p-4 w-full'>
          <div className='w-full relative h-96'>
            <Image
              src={'/assets/amd-2.jpeg'}
              alt='PDF OCR for mortgage company'
              layout='fill'
              objectFit='contain'
            />
          </div>
        </div>
      </main>
      <BannerDownload
        text1='STREAMLINE MORTGAGES DOCUMENTS PROCESSING'
        text2='Contact Us for demo'
      />
      <Footer />
    </div>
  )
}

export default PdfOcr
