import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Footer from '../components/Footer'
import Hiring from '../components/home/hiring'
import Navbar from '../components/Navbar'
import { CLIENTS_LOGOS, SITE_TITLE } from '../lib/constants'
import styles from '../styles/Home.module.css'
import {
  faWifi,
  faFileExport,
  faMobile,
  faSliders,
  faCertificate,
  faMapMarkedAlt,
  faEnvelope,
  faDraftingCompass,
  faFile,
} from '@fortawesome/free-solid-svg-icons'

import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { useState } from 'react'
import { submitContactForm } from './api/api-helper'
import Carousel from '../components/common/Carousel'

const Solutions: NextPage = () => {
  const [name, setName] = useState<string>('')
  const [email, setEmail] = useState<string>('')
  const [notes, setNotes] = useState<string>('')
  const [message, setMessage] = useState<string>()
  const resetForm = () => {
    setName('')
    setNotes('')
    setEmail('')
  }
  const onSubmit = (name: string, email: string, message: string) => {
    setMessage('processing...')

    const contactInput = {
      name,
      email,
      notes,
      website: 'andmap.co',
    }

    submitContactForm(contactInput)
      .then((result) => {
        resetForm()
        setMessage('Thanks, we will contact you soon.')
      })
      .catch((error) => setMessage(error.message))
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>{SITE_TITLE}</title>

        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Navbar />

      <main className={styles.main}>
        <div className='grid grid-cols-1 gap-4 lg:grid-cols-2'>
          <div className='p-16'>
            <h2 className='text-[16px] text-bold pb-2'>AMG V3.1</h2>
            <p className='text-[30px] mb-8'>ANDMAP MOBILE GIS</p>
            <p className='text-gray-400'>
              AMG is a custom configured {`'`}turn-key{`'`} solution,
              streamlines your Field Mapping and Data Collection works.
            </p>
            <div className='flex'>
              <div className='flex-auto w-64 relative h-64 p-4'>
                <Image
                  src={'/assets/custom.icon.png'}
                  alt='custom icon'
                  layout='fill'
                  objectFit='contain'
                />
              </div>
              <div className='flex-auto w-32 p-8'>
                Custom Style: Control Icon, color, line width, line style by
                Attribute
              </div>
            </div>
          </div>

          <div className='p-16 '>
            <div className='w-full relative h-96'>
              <iframe
                className='w-full h-full'
                src='https://www.youtube.com/embed/bl_RqdSHJj4?rel=0'
              ></iframe>
            </div>
          </div>
        </div>
        <h2 className='text-[30px] text-bold pb-2 uppercase'>features</h2>
        <div className='w-[35px] h-[2px] bg-blue mb-8' />
        <div className='grid grid-cols-1 gap-4 lg:grid-cols-4 p-16'>
          <div className='text-center p-4 relative'>
            <span className='inner-block w-20 h-20 rounded-full border-2 border-blue bg-blue inline-flex justify-center items-center mb-4'>
              <FontAwesomeIcon
                icon={faDraftingCompass}
                className='text-white'
                style={{ fontSize: 36 }}
              />{' '}
            </span>
            <h3 className='h5 text-gray-400 uppercase mb-3'>MAPPING</h3>
            <p className='mb-0'>
              Collect rich points, lines and polygons, Map Annotation: arrow,
              text... Geo-tagged photos...
            </p>
          </div>

          <div className='text-center p-4 relative border-l border-verylightgray'>
            <span className='inner-block w-20 h-20 rounded-full border-2 border-blue bg-blue inline-flex justify-center items-center mb-4'>
              <FontAwesomeIcon
                icon={faWifi}
                className='text-white'
                style={{ fontSize: 36 }}
              />{' '}
            </span>
            <h3 className='h5 text-gray-400 uppercase mb-3'>WORK OFFLINE</h3>
            <p className='mb-0'>
              Field work offline - no internet required, real-time sync
              capability when internet available
            </p>
          </div>
          <div className='text-center p-4 relative border-l border-bray'>
            <span className='inner-block w-20 h-20 rounded-full border-2 border-blue bg-blue inline-flex justify-center items-center mb-4'>
              <FontAwesomeIcon
                icon={faFile}
                className='text-white'
                style={{ fontSize: 36 }}
              />{' '}
            </span>
            <h3 className='h5 text-gray-400 uppercase mb-3'>
              DATA IMPORT/EXPORT
            </h3>
            <p className='mb-0'>
              Collection Forms, Layer Configuration, Import Master / Reference
              data, Export to KMZ, Shapefile...
            </p>
          </div>
          <div className='text-center p-4 relative border-l border-bray'>
            <span className='inner-block w-20 h-20 rounded-full border-2 border-blue bg-blue inline-flex justify-center items-center mb-4'>
              <FontAwesomeIcon
                icon={faSliders}
                className='text-white'
                style={{ fontSize: 36 }}
              />{' '}
            </span>
            <h3 className='h5 text-gray-400 uppercase mb-3'>CUSTOM FORM</h3>
            <p className='mb-0'>
              Attribute Data Type: Label, Text, Number, Pick list, Signature,
              Sketch, Barcode, RFId, Formula, Date, Time, TimeStamp
            </p>
          </div>
        </div>

        <h2 className='text-[30px] text-bold pb-2 uppercase mt-16'>
          WHAT OUR USERS SAY
        </h2>
        <div className='w-[35px] h-[2px] bg-blue ' />
        <div className='grid grid-cols-1 gap-4 lg:grid-cols-3 p-16'>
          <div className='p-8'>
            <p className='text-fontGray font-thin mt-4'>
              {`'`}An Outstanding Mapping and Auditing Tool - Second to None!!
              The Custom Built Site and Dedicated Server has truly played an
              instrumental part in developing a Tool that really works for us.
              This App continually allows us to refine our skills and further
              enhance our field methodology. Truly customised to meet our needs.
              Fantastic assistance from the Developer and quick to provide
              turnaround on any issues and new processes. A must have App!{`'`}
            </p>
            <h2 className='text-bold  font-thin mt-4'>Dave Martin</h2>
            <h3 className='text-blue text-sm'>Lend Lease Group</h3>
          </div>
          <div className='p-8'>
            <p className='text-fontGray font-thin mt-4'>
              {`'`}GIS relevant solution for field data collection Very well
              supported app. The developer will adapt to fit your needs and is
              more than willing to accept input. The only smartphone app that I
              have found that can effectively replace GIS specific (expensive)
              equipment and do so effectively. I look forward to seeing Andmap
              continue to advance. Thanks!{`'`}
            </p>
            <h2 className='text-bold  font-thin mt-4'>Joe Nicholas</h2>
            <h3 className='text-blue text-sm'>National Park Service</h3>
          </div>
          <div className='p-8'>
            <p className='text-fontGray font-thin mt-4'>
              {`'`}I think this is the best GIS data collection app I{`'`}ve
              used. Faster and easier to use then the expensive Windows Mobile
              professional apps on rugged field computers I{`'`}ve used. The
              developers respond to my every inquiry and even add the features
              that I request. Highly recommended if you need a serious GIS data
              collector and geophoto management app with online data storage and
              manager.{`'`}
            </p>
            <h2 className='text-bold  font-thin mt-4'>Emil Robles</h2>
            <h3 className='text-blue text-sm'>Philippines</h3>
          </div>
        </div>

        <h2 className='text-[30px] text-bold pb-2 uppercase mt-16'>
          OUR CLIENTS
        </h2>
        <div className='w-[35px] h-[2px] bg-blue ' />
        <div className='2xl:container 2xl:mx-auto 2xl:px-0 py-3 px-10 w-full'>
          <Carousel data={CLIENTS_LOGOS} />
        </div>
      </main>

      <Footer />
    </div>
  )
}

export default Solutions
