import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Footer from '../components/Footer'
import Hiring from '../components/home/hiring'
import Navbar from '../components/Navbar'
import { CLIENTS_LOGOS, SITE_TITLE } from '../lib/constants'
import styles from '../styles/Home.module.css'
import {
  faWifi,
  faFileExport,
  faMobile,
  faSliders,
  faCertificate,
  faMapMarkedAlt,
  faEnvelope,
  faDraftingCompass,
  faFile,
} from '@fortawesome/free-solid-svg-icons'
import Link from 'next/link'

import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { useState } from 'react'
import { submitContactForm } from './api/api-helper'
import Carousel from '../components/common/Carousel'
import SuwasaDownload from '../components/home/suwasa-download'

const Suwasa: NextPage = () => {
  const [name, setName] = useState<string>('')
  const [email, setEmail] = useState<string>('')
  const [notes, setNotes] = useState<string>('')
  const [message, setMessage] = useState<string>()
  const resetForm = () => {
    setName('')
    setNotes('')
    setEmail('')
  }
  const onSubmit = (name: string, email: string, message: string) => {
    setMessage('processing...')

    const contactInput = {
      name,
      email,
      notes,
      website: 'andmap.co',
    }

    submitContactForm(contactInput)
      .then((result) => {
        resetForm()
        setMessage('Thanks, we will contact you soon.')
      })
      .catch((error) => setMessage(error.message))
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>{SITE_TITLE}</title>

        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Navbar />

      <main className={styles.main}>
        <div className='grid grid-cols-1 gap-4 lg:grid-cols-2'>
          <div className='p-16'>
            <h2 className='text-[30px] text-bold pb-2'>
              Water Distribution Network Mapping
            </h2>
            <p className='text-[14px] mb-8 text-blue'>
              USAID-funded,{' '}
              <a href='https://www.tetratech.com/en/projects/sustainable-water-and-sanitation-in-africa'>
                details...
              </a>
            </p>
            <p className='text-gray-400'>
              The exercise utilizes tablet technologies which reduce paper
              burden and speed up time between data collection and response.
              Over two weeks in November 2013 EBSWC distribution engineers have
              been trained to map the distribution network using{' '}
              <Link href='/solutions'>
                <span className='text-blue'>AMG V3.1</span>
              </Link>
            </p>

            <div className='flex-auto w-full relative h-64 p-4 mt-4'>
              <Image
                src={'/assets/suwasa-3.jpeg'}
                alt='suwasa local image'
                layout='fill'
                objectFit='contain'
              />
            </div>
          </div>

          <div className='p-16 '>
            <div className='w-full relative h-96'>
              <Image
                src={'/assets/projectmap.jpeg'}
                alt='project map'
                layout='fill'
                objectFit='contain'
              />
            </div>
          </div>
        </div>

        <h2 className='text-[30px] text-bold pb-2 uppercase mt-16'>
          Sample Data
        </h2>
        <div className='w-[35px] h-[2px] bg-blue ' />
        <div className='grid grid-cols-1 gap-4 lg:grid-cols-3 p-16'>
          <div className='w-72 relative h-96 p-8'>
            <Image
              src={'/assets/pipeline.png'}
              alt='pipeline'
              layout='fill'
              objectFit='contain'
            />
          </div>

          <div className='w-72 relative h-96 p-8'>
            <Image
              src={'/assets/fittings.png'}
              alt='fitting'
              layout='fill'
              objectFit='contain'
            />
          </div>

          <div className='w-72 relative h-96 p-8'>
            <Image
              src={'/assets/forms.png'}
              alt='form'
              layout='fill'
              objectFit='contain'
            />
          </div>
        </div>
      </main>
      <SuwasaDownload />
      <Footer />
    </div>
  )
}

export default Suwasa
